#!/bin/sh

# make sure we are on the external antenna
/usr/bin/set_antenna ufl

case "$1" in
  start)
    nohup /usr/bin/missing_link_display &
    ;;
  stop)
    exit 1
    ;;
  *)
    exit 1
    ;;
esac

case "$1" in
  start)
    nohup /usr/bin/missing_link &
    ;;
  stop)
    exit 1
    ;;
  *)
    exit 1
    ;;
esac

exit 0
